/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness check.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/data-sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Data Sources
         * @description Per-source live-versus-cache status and snapshot age.
         */
        get: operations["data_sources_health_data_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Observation
         * @description Accept a field report, structure it, and trigger re-planning.
         */
        post: operations["submit_observation_observations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/observations/structure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Structure Report
         * @description Use the configured LLM to convert messy report text into a validated observation.
         */
        post: operations["structure_report_observations_structure_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/observations/structured": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Structured Observation
         * @description Accept a reviewed structured observation and trigger re-planning without another LLM call.
         */
        post: operations["submit_structured_observation_observations_structured_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current Plan
         * @description The current response plan.
         */
        get: operations["current_plan_plan_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/failed-traces/{trace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Failed Execution Trace
         * @description Return a bounded failed-run trace when its id was reported with an error.
         */
        get: operations["failed_execution_trace_plan_failed_traces__trace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/recompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recompute
         * @description Force a recompute. Returns the new plan and its latency.
         */
        post: operations["recompute_plan_recompute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/{plan_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Execution Trace
         * @description Structured, redacted execution trace for one completed plan.
         */
        get: operations["execution_trace_plan__plan_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/{plan_id}/trace/{site_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Site Execution Trace
         * @description Site agent decisions plus plan-wide stages for one completed plan.
         */
        get: operations["site_execution_trace_plan__plan_id__trace__site_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/scenario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scenario
         * @description The active simulated resource scenario.
         */
        get: operations["get_scenario_resources_scenario_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Scenario
         * @description Change capacity, for example marking a boat unavailable, and trigger re-planning.
         */
        patch: operations["update_scenario_resources_scenario_patch"];
        trace?: never;
    };
    "/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sites
         * @description All sites in the study area with both value scores and current evidence.
         */
        get: operations["list_sites_sites_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{site_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Site Evidence
         * @description Fused evidence for one site, including per-cause support, confidence, and citations.
         */
        get: operations["site_evidence_sites__site_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionClass
         * @description Candidate action classes defined by the intervention knowledge base.
         *
         *     The LLM does not extend this list.
         *     New classes are added to the knowledge base with a cited source.
         * @enum {string}
         */
        ActionClass: "monitoring" | "targeted_disease_survey" | "biosecurity_workflow" | "water_quality_investigation" | "physical_damage_assessment" | "temporary_shading";
        /**
         * Assignment
         * @description One boat and team sent to one site to perform one action.
         */
        Assignment: {
            action_class: components["schemas"]["ActionClass"];
            /** Action Id */
            action_id: string;
            /** Boat Id */
            boat_id?: string | null;
            /**
             * Compatibility Rationale
             * @description Why this action was considered compatible, with its knowledge-base provenance.
             */
            compatibility_rationale: string;
            /** Estimated Cost Usd */
            estimated_cost_usd: number;
            /** Estimated Hours */
            estimated_hours: number;
            /**
             * Evidence Summary
             * @description What evidence supported this decision.
             */
            evidence_summary: string;
            priority: components["schemas"]["Priority"];
            /**
             * Remaining Uncertainty
             * @description What we still do not know.
             */
            remaining_uncertainty: string;
            /**
             * Requires Manager Approval
             * @default true
             */
            requires_manager_approval: boolean;
            /** Site Id */
            site_id: string;
            /** Site Name */
            site_name: string;
            /** Team Id */
            team_id?: string | null;
        };
        /** Boat */
        Boat: {
            /**
             * Available
             * @default true
             */
            available: boolean;
            /** Boat Id */
            boat_id: string;
            /** Name */
            name: string;
            /** Operational Hours */
            operational_hours: number;
        };
        /**
         * Cause
         * @description The four competing evidence categories.
         *
         *     These are not mutually exclusive.
         *     Thermal stress and disease can both be well supported at the same site.
         * @enum {string}
         */
        Cause: "thermal" | "disease" | "runoff" | "physical";
        /**
         * CauseEvidence
         * @description One investigator's independent assessment of one cause.
         */
        CauseEvidence: {
            cause: components["schemas"]["Cause"];
            /** Citations */
            citations?: components["schemas"]["EvidenceCitation"][];
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /**
             * Confidence
             * @description How much the investigator trusts its own support score given input quality.
             */
            confidence: number;
            /**
             * Display Summary
             * @description One concise sentence for the hypothesis card.
             */
            display_summary: string;
            /**
             * Key Findings
             * @description One to three concise evidence points for the hypothesis card.
             */
            key_findings: string[];
            /**
             * Rationale
             * @description Full audit rationale retained in the execution trace.
             */
            rationale: string;
            /**
             * Support
             * @description Support score, not a probability. Not normalized against other causes.
             */
            support: number;
        };
        /**
         * DataSourceStatus
         * @description Live-versus-cache standing for one external source.
         */
        DataSourceStatus: {
            /** Note */
            note: string;
            /**
             * Provenance
             * @description Every provenance kind seen for this source in the current evidence snapshot.
             */
            provenance: components["schemas"]["Provenance"][];
            /** Source */
            source: string;
            /**
             * Status
             * @enum {string}
             */
            status: "live" | "cache" | "synthetic_fixture";
        };
        /**
         * DataSourcesHealth
         * @description Per-source provenance standing behind the current plan.
         *
         *     `status` is `no_plan` before the first plan is published, in which case
         *     `sources` is empty. This endpoint never starts a planning run.
         */
        DataSourcesHealth: {
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Sources */
            sources: components["schemas"]["DataSourceStatus"][];
            /**
             * Status
             * @default ok
             * @enum {string}
             */
            status: "ok" | "no_plan";
        };
        /**
         * DeferredSite
         * @description A site that needed attention but did not fit within capacity.
         */
        DeferredSite: {
            /**
             * Fallback Action Id
             * @description For example monitoring only, when intervention was deferred.
             */
            fallback_action_id?: string | null;
            /**
             * Reason
             * @description The binding constraint, stated plainly.
             */
            reason: string;
            /** Site Id */
            site_id: string;
            /** Site Name */
            site_name: string;
        };
        /** DiveTeam */
        DiveTeam: {
            /**
             * Available Hours
             * @description Team-level elapsed in-water hours available in the planning window. These are not diver-hours and must not be multiplied by diver_count.
             */
            available_hours: number;
            /**
             * Available Hours Basis
             * @description The unit represented by available_hours.
             * @default team_elapsed_hours
             * @constant
             */
            available_hours_basis: "team_elapsed_hours";
            /** Certifications */
            certifications?: string[];
            /** Diver Count */
            diver_count: number;
            /** Name */
            name: string;
            /** Team Id */
            team_id: string;
        };
        /** EcologicalMeasurements */
        EcologicalMeasurements: {
            /** Coral Cover Pct */
            coral_cover_pct: number;
            provenance: components["schemas"]["ProvenanceMetadata"];
            sampling: components["schemas"]["SamplingMetadata"];
            /** Species Richness */
            species_richness: number;
        };
        /**
         * EvidenceCitation
         * @description Where one piece of supporting evidence came from.
         *
         *     Source metadata is preserved rather than discarded after a lookup.
         *     For AGRRA records this means submission date, review status, and the
         *     reporting organization survive into the dashboard.
         */
        EvidenceCitation: {
            /** Observed At */
            observed_at?: string | null;
            /** @default live */
            provenance: components["schemas"]["Provenance"];
            /**
             * Reference
             * @description URL or record identifier.
             */
            reference?: string | null;
            /** Reporting Organization */
            reporting_organization?: string | null;
            /**
             * Review Status
             * @description For reviewed datasets, the record's review state.
             */
            review_status?: string | null;
            /**
             * Source
             * @description Human-readable source name, for example 'AGRRA SCTLD map'.
             */
            source: string;
        };
        /**
         * ExecutionTrace
         * @description Complete trace retained for one response plan.
         */
        ExecutionTrace: {
            /**
             * Completed At
             * Format: date-time
             */
            completed_at: string;
            /** Latency Ms */
            latency_ms: number;
            /** Offline */
            offline: boolean;
            /** Parent Plan Id */
            parent_plan_id?: string | null;
            /** Plan Id */
            plan_id?: string | null;
            /** Scenario Id */
            scenario_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** @default succeeded */
            status: components["schemas"]["TraceStatus"];
            /** Steps */
            steps: components["schemas"]["TraceStep"][];
            /** Trace Id */
            trace_id: string;
            /** Trigger */
            trigger?: string | null;
        };
        /**
         * FieldReport
         * @description A raw observation as submitted by a diver, scientist, or restoration team.
         */
        FieldReport: {
            /** Image Refs */
            image_refs?: string[];
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Observer */
            observer: string;
            /**
             * @description Demo reports are synthetic and labeled as such everywhere they appear.
             * @default synthetic
             */
            provenance: components["schemas"]["Provenance"];
            /** @description Record-level source and retrieval metadata from the fixture envelope. */
            provenance_metadata?: components["schemas"]["ProvenanceMetadata"] | null;
            /** Report Id */
            report_id: string;
            /** Site Id */
            site_id: string;
            /** Text */
            text: string;
        };
        /**
         * FusedEvidence
         * @description Deterministic reconciliation of the four investigator outputs for one site.
         *
         *     Fusion aggregates the summary.
         *     It does not normalize the four support scores against each other, because they
         *     are not competing shares of a single probability mass.
         */
        FusedEvidence: {
            /**
             * Ambiguity
             * @description How close the leading causes are. High ambiguity is what the Coordinator resolves by requesting more evidence.
             */
            ambiguity: number;
            /** By Cause */
            by_cause: {
                [key: string]: components["schemas"]["CauseEvidence"];
            };
            /**
             * Dominant Causes
             * @description Causes whose support clears the acting threshold. May contain more than one.
             */
            dominant_causes: components["schemas"]["Cause"][];
            /**
             * Fused At
             * Format: date-time
             */
            fused_at: string;
            /** Lowest Confidence */
            lowest_confidence: number;
            /** Site Id */
            site_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthStatus
         * @description Liveness payload.
         */
        HealthStatus: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** Inventory */
        Inventory: {
            /**
             * Monitoring Kits
             * @default 0
             */
            monitoring_kits: number;
            /**
             * Sampling Kits
             * @default 0
             */
            sampling_kits: number;
            /**
             * Shade Units
             * @default 0
             */
            shade_units: number;
        };
        JsonValue: unknown;
        /**
         * MonitoringProgram
         * @description Which monitoring programme produced an ecological measurement.
         *
         *     These are not interchangeable. CREMP uses fixed, permanently staked transects
         *     with photo point counts. NCRMP uses stratified random sampling with linear
         *     point intercept. A cover value from one is not a like-for-like substitute for
         *     a cover value from the other, which is why the programme is a required field
         *     on every measurement and travels to the dashboard rather than living in a note.
         * @enum {string}
         */
        MonitoringProgram: "CREMP" | "NCRMP";
        /**
         * ObservationAccepted
         * @description Result of submitting one field report, including the plan it produced.
         */
        ObservationAccepted: {
            plan: components["schemas"]["ResponsePlan"];
            /**
             * Replan Latency Ms
             * @description Measured server-side so the dashboard does not include network noise.
             */
            replan_latency_ms?: number | null;
            /** Report Id */
            report_id: string;
        };
        /**
         * Priority
         * @enum {string}
         */
        Priority: "low" | "medium" | "high";
        /**
         * Provenance
         * @description Where a value actually came from.
         *
         *     Every externally sourced value carries one of these.
         *     SIMULATED and SYNTHETIC are never presented to a user as real.
         * @enum {string}
         */
        Provenance: "live" | "cache" | "simulated" | "synthetic";
        /**
         * ProvenanceMetadata
         * @description Structured origin metadata for one value or coherent record.
         *
         *     `fetched_at` records when an external value was retrieved.
         *     `observed_at` records when the source says the condition occurred.
         *     They are deliberately separate because snapshot age and observation age are
         *     different facts.
         */
        ProvenanceMetadata: {
            /** Fetched At */
            fetched_at?: string | null;
            kind: components["schemas"]["Provenance"];
            /** Note */
            note?: string | null;
            /** Observed At */
            observed_at?: string | null;
            /**
             * Source
             * @description Human-readable source or fixture author.
             */
            source: string;
            /** Source Url */
            source_url?: string | null;
        };
        /**
         * RecomputeRequest
         * @description Optional inputs for a forced plan recompute.
         */
        RecomputeRequest: {
            /**
             * Execution Mode
             * @default configured
             * @enum {string}
             */
            execution_mode: "configured" | "live_llm";
            /**
             * Scenario Id
             * @default demo_default
             */
            scenario_id: string;
            /** Site Ids */
            site_ids?: string[];
        };
        /**
         * ReportStructureResult
         * @description Validated observation extracted from one raw report by the configured LLM.
         */
        ReportStructureResult: {
            /** Attempt Count */
            attempt_count: number;
            /** Extraction Confidence */
            extraction_confidence: number;
            /** Input Tokens */
            input_tokens?: number | null;
            /** Latency Ms */
            latency_ms: number;
            /** Model */
            model: string;
            observation: components["schemas"]["StructuredObservation"];
            /** Output Tokens */
            output_tokens?: number | null;
            /** Provider */
            provider: string;
            /** Report Id */
            report_id: string;
        };
        /**
         * ResourceChangeRequest
         * @description Resource scenario selected for the next planning window.
         */
        ResourceChangeRequest: {
            /** Description */
            description: string;
            /** Scenario Id */
            scenario_id: string;
        };
        /**
         * ResourceChangeResult
         * @description The plan produced by a capacity change, with the scenario now in force.
         */
        ResourceChangeResult: {
            /**
             * Banner
             * @description Simulated-data banner. Never drop this in the UI.
             */
            banner: string;
            plan: components["schemas"]["ResponsePlan"];
            scenario: components["schemas"]["ResourceScenario"];
        };
        /**
         * ResourceScenario
         * @description The capacity available for one planning window.
         */
        ResourceScenario: {
            /** Boats */
            boats: components["schemas"]["Boat"][];
            /** Budget Usd */
            budget_usd: number;
            /** Daylight Hours */
            daylight_hours: number;
            /** Dive Teams */
            dive_teams: components["schemas"]["DiveTeam"][];
            inventory: components["schemas"]["Inventory"];
            /** Label */
            label: string;
            /** @description Simulated for every scenario shipped with the prototype. */
            provenance: components["schemas"]["Provenance"];
            /** Scenario Id */
            scenario_id: string;
        };
        /**
         * ResponsePlan
         * @description A complete allocation for one planning window.
         */
        ResponsePlan: {
            /** Assignments */
            assignments: components["schemas"]["Assignment"][];
            /**
             * Binding Constraints
             * @description Which constraints were tight, so trade-offs are explainable.
             */
            binding_constraints?: string[];
            /** Deferred */
            deferred?: components["schemas"]["DeferredSite"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Plan Id */
            plan_id: string;
            /**
             * Replan Latency Ms
             * @description Evidence submitted to plan displayed. Reported metric, see docs/evaluation.md.
             */
            replan_latency_ms?: number | null;
            /**
             * Replan Trigger
             * @description What caused this recompute, when it was not the first plan.
             */
            replan_trigger?: string | null;
            /**
             * Scenario Banner
             * @description Simulated-data banner text, carried on the plan so it cannot be dropped.
             */
            scenario_banner: string;
            /** Scenario Id */
            scenario_id: string;
            /**
             * Total Strategic Value
             * @description Objective value achieved. Comparable against the naive baseline.
             */
            total_strategic_value: number;
        };
        /**
         * RestorationInvestment
         * @description Prior management commitment. Feeds strategic_value only.
         *
         *     No public dataset publishes per-site restoration spend, so every value shipped
         *     with the prototype is simulated and its provenance says so.
         */
        RestorationInvestment: {
            provenance: components["schemas"]["ProvenanceMetadata"];
            /** Value */
            value: number;
        };
        /**
         * SamplingMetadata
         * @description How a measurement was obtained, as data rather than as prose.
         *
         *     Every field here exists because a reviewer could reasonably disagree with the
         *     choice it records. Sample size and spread are first-class so that downstream
         *     consumers can see how thin a measurement is, without the model imposing a
         *     confidence weight of its own.
         */
        SamplingMetadata: {
            /** Habitat Types */
            habitat_types: string[];
            /**
             * Includes Millepora
             * @description CREMP cover includes Millepora, a hydrocoral. NCRMP figures here exclude it.
             */
            includes_millepora: boolean;
            /**
             * Matching Distance Km
             * @description Zero when the site is named in the source data.
             */
            matching_distance_km: number;
            /**
             * Matching Method
             * @description How this site was matched to the source data, so a reviewer can disagree with it.
             */
            matching_method: string;
            program: components["schemas"]["MonitoringProgram"];
            /** Reference Years */
            reference_years: number[];
            /**
             * Richness Definition
             * @description Neither programme publishes a richness field. This states how ours was counted.
             */
            richness_definition: string;
            /**
             * Sample N
             * @description Number of stations or sample units pooled.
             */
            sample_n: number;
            /**
             * Sample Sd Pct
             * @description Standard deviation of cover across the pooled units.
             */
            sample_sd_pct?: number | null;
            /**
             * Sample Unit
             * @description What one unit of sample_n is: station, or sample unit.
             */
            sample_unit: string;
            /**
             * Sampling Design
             * @description How the programme samples, in one phrase. Not interchangeable between programmes.
             */
            sampling_design: string;
            /** Station Ids */
            station_ids?: string[];
        };
        /**
         * ScenarioView
         * @description The active simulated capacity scenario and its mandatory banner.
         */
        ScenarioView: {
            /**
             * Banner
             * @description Simulated-data banner. Never drop this in the UI.
             */
            banner: string;
            scenario: components["schemas"]["ResourceScenario"];
        };
        /**
         * SiteExecutionTrace
         * @description Site-filtered view of a completed execution trace.
         */
        SiteExecutionTrace: {
            /** Offline */
            offline: boolean;
            /** Parent Plan Id */
            parent_plan_id?: string | null;
            /** Plan Id */
            plan_id: string;
            /** Scenario Id */
            scenario_id: string;
            /** Site Id */
            site_id: string;
            status: components["schemas"]["TraceStatus"];
            /** Steps */
            steps: components["schemas"]["TraceStep"][];
            /** Trace Id */
            trace_id: string;
            /** Trigger */
            trigger?: string | null;
        };
        /**
         * SiteLocation
         * @description A point convention applied to an area, with the convention recorded.
         */
        SiteLocation: {
            /** Latitude */
            latitude: number;
            /**
             * Location Basis
             * @description The convention used to reduce an area to a point. Not a survey position.
             */
            location_basis: string;
            /** Longitude */
            longitude: number;
            provenance: components["schemas"]["ProvenanceMetadata"];
            /** Zone Name In Source */
            zone_name_in_source?: string | null;
            /** Zone Span Km */
            zone_span_km?: number | null;
        };
        /**
         * SiteScores
         * @description Two scores, deliberately not blended into one.
         *
         *     ecological_value = 0.6 * normalized(coral_cover) + 0.4 * normalized(species_richness)
         *     strategic_value  = 0.7 * ecological_value       + 0.3 * normalized(restoration_investment)
         *
         *     Restoration investment is a management consideration, not an ecological one.
         *     Blending them into a single number quietly mixes two kinds of judgment.
         *
         *     The weights are stated prototype assumptions, not scientific claims, and are
         *     labeled as such on the dashboard and in the pitch.
         */
        SiteScores: {
            /** Ecological Value */
            ecological_value: number;
            /** Site Id */
            site_id: string;
            /** Strategic Value */
            strategic_value: number;
            /**
             * Weights Are Prototype Assumptions
             * @description Always true. Present in the payload so the dashboard cannot forget to say so.
             * @default true
             */
            weights_are_prototype_assumptions: boolean;
        };
        /**
         * SiteView
         * @description One study-area site with its scores and its standing in the current plan.
         *
         *     This extends `ReefSite` rather than nesting it, because the site's own
         *     fields are serialized at the top level of the response.
         */
        SiteView: {
            current_assignment?: components["schemas"]["Assignment"] | null;
            deferred?: components["schemas"]["DeferredSite"] | null;
            /**
             * Dominant Causes
             * @description Causes currently in play. More than one can be, and none is valid.
             */
            dominant_causes: components["schemas"]["Cause"][];
            /**
             * Has Active Restoration
             * @description Whether active nursery or outplant work exists at this site. This is prior management commitment, not ecological value. Do not name specific organizations unless verified per site.
             * @default false
             */
            has_active_restoration: boolean;
            /**
             * Latitude
             * @description Serialized convenience field for the flat API site shape.
             */
            readonly latitude: number;
            location: components["schemas"]["SiteLocation"];
            /**
             * Longitude
             * @description Serialized convenience field for the flat API site shape.
             */
            readonly longitude: number;
            measurements: components["schemas"]["EcologicalMeasurements"];
            /** Name */
            name: string;
            restoration_investment: components["schemas"]["RestorationInvestment"];
            scores: components["schemas"]["SiteScores"];
            /** Site Id */
            site_id: string;
        };
        /**
         * StructuredObservation
         * @description Structured signals extracted from one field report.
         *
         *     Every field is optional because a real report rarely mentions everything.
         *     Absence means "not reported", never "reported as zero".
         */
        StructuredObservation: {
            /** Affected Taxa */
            affected_taxa?: string[];
            /** Bleaching Pct */
            bleaching_pct?: number | null;
            /** Broken Coral Observed */
            broken_coral_observed?: boolean | null;
            /** Compared To Previous Dive */
            compared_to_previous_dive?: string | null;
            /**
             * Extraction Notes
             * @description What the extractor was unsure about. Surfaced, not swallowed.
             */
            extraction_notes?: string | null;
            /** Lesion Description */
            lesion_description?: string | null;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Paling Pct */
            paling_pct?: number | null;
            /** @description Record-level source and retrieval metadata from the fixture envelope. */
            provenance_metadata?: components["schemas"]["ProvenanceMetadata"] | null;
            /** Report Id */
            report_id: string;
            /** Sediment Note */
            sediment_note?: string | null;
            /** Site Id */
            site_id: string;
            /**
             * Spatial Progression
             * @description For example 'spreading westward since last dive'.
             */
            spatial_progression?: string | null;
            /** Tissue Loss Observed */
            tissue_loss_observed?: boolean | null;
            /** Turbidity Note */
            turbidity_note?: string | null;
        };
        /**
         * StructuredObservationSubmission
         * @description A raw report and the reviewed extraction to use for re-planning.
         */
        StructuredObservationSubmission: {
            observation: components["schemas"]["StructuredObservation"];
            report: components["schemas"]["FieldReport"];
        };
        /**
         * TokenUsage
         * @description Provider-reported token usage accumulated across validation retries.
         */
        TokenUsage: {
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
        };
        /**
         * TraceExecutor
         * @description What actually executed a trace stage.
         * @enum {string}
         */
        TraceExecutor: "deterministic" | "llm" | "fixture" | "optimizer";
        /**
         * TraceStage
         * @description Named stages visible to API clients and the future dashboard.
         * @enum {string}
         */
        TraceStage: "evidence_tools" | "thermal_investigator" | "disease_investigator" | "runoff_investigator" | "physical_investigator" | "evidence_fusion" | "policy_eligibility" | "coordinator" | "optimizer";
        /**
         * TraceStatus
         * @enum {string}
         */
        TraceStatus: "succeeded" | "failed";
        /**
         * TraceStep
         * @description One completed and validated pipeline boundary.
         */
        TraceStep: {
            /** Attempt Count */
            attempt_count?: number | null;
            /**
             * Completed At
             * Format: date-time
             */
            completed_at: string;
            /** Error Message */
            error_message?: string | null;
            /** Error Type */
            error_type?: string | null;
            executor: components["schemas"]["TraceExecutor"];
            /** Inputs */
            inputs?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Latency Ms */
            latency_ms: number;
            /** Model */
            model?: string | null;
            /** Output */
            output?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Provider */
            provider?: string | null;
            /** Rationale */
            rationale?: string | null;
            /** Sequence */
            sequence: number;
            /** Site Id */
            site_id?: string | null;
            stage: components["schemas"]["TraceStage"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** @default succeeded */
            status: components["schemas"]["TraceStatus"];
            token_usage?: components["schemas"]["TokenUsage"] | null;
            /** Validation Checks */
            validation_checks?: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    data_sources_health_data_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataSourcesHealth"];
                };
            };
        };
    };
    submit_observation_observations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FieldReport"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    structure_report_observations_structure_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FieldReport"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportStructureResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_structured_observation_observations_structured_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StructuredObservationSubmission"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_plan_plan_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponsePlan"];
                };
            };
        };
    };
    failed_execution_trace_plan_failed_traces__trace_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionTrace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recompute_plan_recompute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RecomputeRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponsePlan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execution_trace_plan__plan_id__trace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionTrace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    site_execution_trace_plan__plan_id__trace__site_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteExecutionTrace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scenario_resources_scenario_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioView"];
                };
            };
        };
    };
    update_scenario_resources_scenario_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResourceChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceChangeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sites_sites_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteView"][];
                };
            };
        };
    };
    site_evidence_sites__site_id__evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FusedEvidence"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
